### ISSUE TITLE
segment results

### ISSUE THREAD

**Issue by gmehak** [amanshenoy/multilogue-net#10]
Hi Aman,
I am trying to reproduce the results of the paper. I see you are taking per time step results for each video. I wanted to do some error analysis, i.e. analyze which frames of the video are doing bad. However, I don't see any kind of segment level results in the code. Just wanted to know if there is some way out? or you just worked with the pickle files (where you concatenated all the frames of the video and extrapolated the frame level prediction to each timestep?) ? 

Secondly, the hyper parameters for each emotion classification remain the same as that given for 'Happiness'? Or if they are different, will it be possible to provide them?

**Comment by amanshenoy** [comment]
Hey @gmehak, 
The model takes as input the video features and not the individual frames. Video features exist not on a per frame basis but instead on a per utterance basis, that is - for every utterance there exists a video feature which uses all the frames that come within that utterance. These video features (on a per utterance basis) were obtained directly from the CMU-Multimodal SDK (https://github.com/A2Zadeh/CMU-MultimodalSDK) and the SDK must have ways of being able to obtain the raw footage for analysis. 

Secondly, regarding the hyper-parameters - we had actually obtained different sets of hyper-parameters using basic grid search but due to offices being closed during paper submission and the conference, a lot of the details and files became inaccessible to us, leading us to never be able to report it in the paper or the repository. I apologise for this, but if it helps the hyper-parameters performed decently at the default (ones in the script) hyper-parameter settings themselves, just that the results in the paper were not reported on these hyper-param settings.

**Comment by gmehak** [comment]
Hi Aman, thanks for the reply. I do have the mapping from the video id to the original video. However, the data I have references multiple sentences from a video, hence I can see multiple video ids corresponding to different timesteps of the video where the sentence might have been spoken. However, I see only 1 video id in the pickle files. hence, I am little confused.

**Comment by amanshenoy** [comment]
I'm not sure why that's happening, did you get the data from the sdk where labels are at 'utterance' level? I remember there being an option to be able to extract labels at various levels (utterance and time basis were 2 that i remember)

**Comment by gmehak** [comment]
Oh, I figured it out. The data is right. The pickle files contain per segment data (one vector as averaged over that segment) and concatenates all the vectors for different segments in a video. Thanks, I could get the required information.
