### ISSUE TITLE
Weighted Accuracy v.s. Standard Accuracy

### ISSUE THREAD

**Issue by Redaimao** [amanshenoy/multilogue-net#12]
Hi,
Thanks for your wonderful work!
I noticed that the results in your paper are weighted accuracy.
I was trying to run your code, where the weighted results and the standard accuracy are both shown.
I wonder what is the difference to evaluate w.r.t. these two metrics, and what are the standard accuracy results on mosei for classification, regression, and emotion that are not reported?

Regards.

**Comment by amanshenoy** [comment]
Hey!
The primary reason of mentioning weighted accuracy is because of the biases due to class frequencies. 

The uncommon emotions such as _fear_ have a label of 0 most of the time. Because of this, the model can over-fit and learn to produce 0's always and still get a decent accuracy on _fear_. This can cause lesser frequent classes to have high class-specific accuracy even when the model has not learned much about it. 

To balance this biasing effect we weigh the accuracy of a particular class with the number of examples (frequency) of that class (and further normalise appropriately). This acts as a more unbiased and balanced metric for judgement. 

A similar but inverted idea is used for the loss. The less frequent, the more the loss should penalise errors on it (to force learning), so the loss is weighted by inverse frequency. 

Hope this answers your question!
