### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by pipijiev12** [amanshenoy/multilogue-net#31]
Is it possible to get data without using Git LFS?

Are there other ways to get the data? For example, cloud disk and so on

**Comment by amanshenoy** [comment]
Hey, sorry for the delayed response - but the paper and code were published amidst COVID, so the code and data had limited scope to be refactored and re-uploaded. Since I have left the organization with which this was published, git-lfs is the only way to be able to get them (I do not have access to the original files beyond git-lfs from this repo)

Our data largely takes from the CMU-Multimodal-SDK though, might be of help if you arent already familiar with it. (https://github.com/A2Zadeh/CMU-MultimodalSDK)
