### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'

### ISSUE THREAD

**Issue by ShantanuShinde** [amanshenoy/multilogue-net#5]
I am getting the following error when unpickling the .pkl files
Is it a version problem? Which pickle version is used? If not then what is wrong?

**Comment by amanshenoy** [comment]
Hey! 

The requirements.txt is a part of the repository and this is not a version problem. This is a problem in the pickle files themselves, either while dumping them or while upload using git-lfs. The only solution to this is that we re-upload or re-create the pickle files causing problems. Errors with the pickle files have been observed with previous issues too. 

A completely rewritten version of the repository will be uploaded soon taking care of this and other issues. Due to current conference work, this will take around two weeks and I apologize for having this error in the first place.

WIll close this issue only once resolved

**Comment by ShantanuShinde** [comment]
is there any other place I can get the dataset? if not, can you create a Google Drive of the files and share the link?

**Comment by amanshenoy** [comment]
> is there any other place I can get the dataset? if not, can you create a Google Drive of the files and share the link?

Yeah. Due to travel restrictions I currently don't have access to the files. But all the pickle files were generated using the CMU Multimodal SDK, the pickle files were uploaded only to simplify the process.

**Comment by ShantanuShinde** [comment]
can you tell me the process of generating the dataset so I can do it myself?

**Comment by amanshenoy** [comment]
As mentioned, CMU Multimodal SDK (https://github.com/A2Zadeh/CMU-MultimodalSDK) was used to generate all the pickle files. Instructions were followed as mentioned in the readme of the SDK and all the labels were utterance aligned (aligning method used was averaging).

**Comment by ShantanuShinde** [comment]
The problem got solved. The files don't really have a problem. As they are large in size, GitHub stores them at separate location, so just downloading the repo doesn't download the complete files, hence I was getting the error. I had to use **Git LFS** in order to download the complete file and now it is working. 
I had to:

1. Install Git LFS
2. Add path
3. Go to the cloned repo and type commands: `git lfs install` `git lfs fetch` `git lfs pull`

And now it is loading
