### ISSUE TITLE
15 seconds/epoch for categorical training

### ISSUE THREAD

**Issue by FionaHuang97** [amanshenoy/multilogue-net#9]
Hi, 

I am using the given parameters and a GV100 instance from AWS, but each epoch can take around 3 minutes instead of 15 seconds as you mentioned.

MOSEI Categorical:  14%|█████████████▊                                                                 | 7/50 [24:19<2:29:02, 207.98s/it]

Could you please give me some suggestions on what might the reason? Or share with me your setting to reach 15s per epoch.

Thank you so much for sharing your work!

**Comment by amanshenoy** [comment]
Hmm, not really sure whats happening. The configuration that achieved the results and the timings are the default ones set in the code. 

Are timings significantly worse for all the 3 training scripts?

**Comment by BastianBN** [comment]
This issue seems quite old, but I do have the same problem on categorical and emotion classifications and using a V100 GPU.
I don't really know the technical differences between a GV100 and a V100, but it does seem to take around 120s by epoch on my side, both on categorical and emotion, which is really far from 15 seconds, even with some technical differences between 2 GPUs that have the same architecture.

I'm using the default settings. It can maybe come from the fact that I'm not exactly using the same requirements that are in the txt document since I had dependencies problems when trying to pip install it. (specially with mkl packages)

Although, thank you for sharing your code and everything, really helps !

**Comment by amanshenoy** [comment]
Hey, to be honest, I wasnt really sure if there was a difference but on looking into it, it seems like they both are different GPU's. GV100's are from NVIDIA's Quadro line of GPU's while V100's are from the Tesla line. Not really sure why the performance is so different though.
